[USER_DB]
host = "localhost"
port = "15433"
user = "hive"
passw = "hivepassword"
dbname = "users"

[AUTORIZATION]
register_codes = ["12345678", "87654321"]

[MISCELLANEOUS]
logo = "static/new-linkedby.png"
subject = "default"
title = "Título Padrão"